/// <reference types="vite/client" />

declare const __APP_VERSION__: string;

/**
 * Generated by `moduleRegistryPlugin` (scripts/module-registry-plugin.mjs):
 * the active variant's module namespaces keyed by `./modules/<id>/module.ts`.
 */
declare module 'virtual:module-registry' {
    export const moduleFiles: Record<string, Record<string, unknown>>;
}
